const data = [{"chinese": "吃饭", "translation": "To eat something"},
{"chinese": "同学们", "translation": "Fellow classmates"},
{"chinese": "学校后面的饭店 ", "translation": "Restaurant at the back of the school"},
{"chinese": "这里", "translation": "Here"},
{"chinese": "这个", "translation": "this (one)"},
{"chinese": "好多", "translation": "Many"},
{"chinese": "[something]，那今天[something]", "translation": "Then/so, today (replicable)"},
{"chinese": "怎么？", "translation": "How’s that?"},
{"chinese": "你先吃一点儿", "translation": "Eat something first"},
{"chinese": "这些 [noun]", "translation": "These (things) "},
{"chinese": "你想去，那你去!", "translation": "You want to go, then you go!"},
{"chinese": "七八块", "translation": "Seven or eight dollars/RMB/Money"},
{"chinese": "在桌子上有五十块钱", "translation": "On the table, there’s 50 dollars/RMB/Money"},
{"chinese": "有人", "translation": "Someone"},
{"chinese": "是谁", "translation": "Who is it/Who’s that?"},
{"chinese": "Billy 在这里", "translation": "Billy is here"},
{"chinese": "几点钟？", "translation": "What time?"},
{"chinese": "四十五分钟后我去那里", "translation": "I’ll be there in 45 minutes"},
{"chinese": "你去哪里?", "translation": "Where are you going?"},
{"chinese": "朋友请我", "translation": "My friend invited me"},
{"chinese": "飞机上的第六个人", "translation": "Sixth person on the plane"},
{"chinese": "你什么时候回来？", "translation": "When are you coming back?"},
{"chinese": "想喝多了", "translation": "Drink too much (to get drunk)"},
{"chinese": "来电话的是妈妈", "translation": "It was mum who called (phone)"},
{"chinese": "她是老师的女儿", "translation": "She is a/the teacher’s daughter"},
{"chinese": "他没开车", "translation": "He didn’t drive (But he can if he wanted, he chose not to)"},
{"chinese": "电影院", "translation": "Movie theatre (Movie court)"},
{"chinese": "我在电影院前面", "translation": "I’m in the front of the cinema/movie theatre"},
{"chinese": "我不想在家里", "translation": "I don’t want to be at home"},
{"chinese": "很高兴我们去看电影！", "translation": "I’m happy we came to see a movie"},
{"chinese": "我的同学们来了吗？", "translation": "Have my classmates arrived?"},
{"chinese": "我不想请他们。", "translation": "I don’t want to invite them"},
{"chinese": "星期一下午", "translation": "Monday afternoon"},
{"chinese": "在家里学习了吗？", "translation": "Did you study at home?"},
{"chinese": "我想去学校前面的医院看医生", "translation": "I want to see a doctor at the front of the school"},
{"chinese": "星期一中午，怎么样？", "translation": "What about Monday, at noon?"},
{"chinese": "现在下雨了", "translation": "Now it’s raining"},
{"chinese": "我的衣服很少", "translation": "I am wearing little clothes"},
{"chinese": "你住在哪儿？", "translation": "Where do you live?"}];

module.exports = data;